name: Build Orion

on:
  push

jobs:

  release-linux-amd64:
    - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/abenstex".insteadOf "https://github.com/abenstex"
    name: release linux/amd64
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v2
        - uses: wangyoucao577/go-release-action@v1.12
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            goos: linux
            goarch: arm
            release_tag: v0.0.1