name: Build Orion

on:
  push

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: arm
          release_tag: v0.0.1
          pre_command: git config --global url."https://${{ secrets.3117e262174f1d4a6381a0c5e2e46ecd3917e113 }}:x-oauth-basic@github.com/abenstex".insteadOf "https://github.com/abenstex"
